### ISSUE TITLE
Dismiss error message across all Playground editor tabs

### ISSUE THREAD

**Issue by kevinwlau** [OpenLiberty/iguide-microprofile-config#137]
When an error message is shown in the playground tabbed editor, it is displayed across all the tabs. They will all clear simultaneously when the error is fixed.

Currently when the error is dismissed with the X button, it only dismisses the error message in the current editor, but should dismiss them from all the editor tabs.

**Comment by kevinwlau** [comment]
Some things to consider for this work:
- Currently the **error is uniform across tabs**, and they are **cleared simultaneously when the error is fixed upon Run**. Both of these implementations are specific to this guide at the moment.
- Should there be an option to enable or disable synced error messages across all the tabs? (should move this issue into [OpenLiberty/iguides-common](https://github.com/OpenLiberty/iguides-common) if so)
  - in case we should want the possibility to have unique error messages per editor tab

**Comment by amyreit** [comment]
I think that this is a non-issue now. First - the playground is single tab now and I checked on multitab editors and the error is not on both tabs

**Comment by steven1046** [comment]
This issue seems specific to playgrounds and not readonly files.

**Comment by lavenal** [comment]
The fix is to support specific error in each editor. Each editor can also display multiple errors. 

When the user hits 'Run' and there is an error in a file, it also switches the editor to the first file with the error.  User can either click other files to check for additional error or once the user fixes the issue, they can hit run again and it would switch to the second file.
