### ISSUE TITLE
Playground Changes

### ISSUE THREAD

**Issue by kevinwlau** [OpenLiberty/iguide-microprofile-config#68]
- [x] split code lines to fit in editor
- [x] change editor filenames
- [x] reword bullet points
- [x] say 'default value' on first bullet
- [x] load property values initially
- [x] require @Inject for properties to be valid
- - [ ] ~add Editor error with button to auto-fix~
- - [ ] ~set default to String~
- - NOTE: decided the two above are too invasive - requires replacing entire java file content with auto-generated code, overriding user input.
- [x] Implement config_ordinal processing in the playground.  
- - [x] Update the instructions to indicate that they can set this value as part of the playground.

**Comment by dmorgant** [comment]
Other things to verify since we reviewed the original playground submitted:

- [ ] The environment properties file has a port value initially loaded
- [ ] Adding 'default value' to 1st bullet (@Inject @ConfigProperty bullet)
- [ ] Remove 'Save' from the menu bar in the editors.   Have 'Run' only.
- [ ] Bulleted list include the TYPE of config source (properties file, env variable, system property)

- [ ] Rename the files in the tabs to be the actual names of the files (CarTypes.java, META-INF/microprofile-config.properties, etc)
